build & pack9

diff --git a/.github/workflows/build-environment.yml b/.github/workflows/build-environment.yml
--- a/.github/workflows/build-environment.yml
+++ b/.github/workflows/build-environment.yml
@@ -27,7 +27,7 @@ jobs:
             sudo apt-get install -y dotnet-sdk-8.0
           elif [[ "${{ inputs.LANGUAGE }}" == "java" ]]; then
             echo "Setting up Java"
-            sudo apt-get install -y openjdk-11-jdk maven
+            sudo apt-get install -y openjdk-11-jdk 
           elif [[ "${{ inputs.LANGUAGE }}" == "python" ]]; then
             echo "Setting up Python" 
             sudo apt-get install -y python3-pip
@@ -45,25 +45,66 @@ jobs:
             echo "Language not supported!"
             exit 1
           fi
+      - name: Set package name and version
+        id: set_name
+        run: |
+            echo "Checking GITHUB_REF: $GITHUB_REF"
+            FOLDER_NAME="nexus-git-development"
+  
+            if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+              TAG_NAME="${GITHUB_REF#refs/tags/}"
+              git fetch origin master
+              MASTER_COMMIT=$(git rev-parse origin/master)
+              TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
+              if [[ "$TAG_COMMIT" == "$MASTER_COMMIT" ]]; then
+                export PACKAGE_ID="nexus-git-${TAG_NAME}"
+                export PACKAGE_VERSION="${TAG_NAME}"
+              else
+                echo "Error: Tags must be created on the master branch."
+                exit 1
+              fi
+            elif [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
+              export PACKAGE_ID="${FOLDER_NAME}.nexus-git"
+              export PACKAGE_VERSION="1.0.0-${GITHUB_RUN_ID}"
+            elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
+              COMMIT_ID=$(echo "${GITHUB_SHA}" | cut -c1-6)
+              export PACKAGE_ID="nexus-git-1.0.0-release-${COMMIT_ID}"
+              export PACKAGE_VERSION="1.0.0-release-${COMMIT_ID}"
+            elif [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
+              exit 1
+            fi 
+  
+            echo "PACKAGE_ID=${PACKAGE_ID}" >> $GITHUB_ENV
+            echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
 
       - name: Build project
         run: |
-            mkdir -p build-output
             if [[ "${{ inputs.LANGUAGE }}" == "dotnet" ]]; then
-              dotnet build --configuration Release -o build-output
+              dotnet build --configuration Release
             elif [[ "${{ inputs.LANGUAGE }}" == "java" ]]; then
-              mvn clean package -DskipTests -DoutputDirectory=build-output
+               mvn clean package \
+                -Dpackage.id=${{ env.PACKAGE_ID }} \
+                -Dpackage.version=${{ env.PACKAGE_VERSION }}
             elif [[ "${{ inputs.LANGUAGE }}" == "python" ]]; then
-              python setup.py install --prefix build-output
+              python setup.py install
             elif [[ "${{ inputs.LANGUAGE }}" == "kotlin" ]]; then
-              gradle build -x test -DbuildDir=build-output
+              gradle build
             elif [[ "${{ inputs.LANGUAGE }}" == "react" || "${{ inputs.LANGUAGE }}" == "javascript" ]]; then
-              npm install
-              npm run build --prefix build-output
+              npm run build
             fi
 
-      - name: Upload build artifact
+
+
+      - name: Create a package
+        run: |
+          mkdir -p build
+          echo "Package ID: $PACKAGE_ID" > build/package_info.txt
+          echo "Package Version: $PACKAGE_VERSION" >> build/package_info.txt
+          # Add other commands to create the actual package, if applicable.
+
+      - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
           name: build-artifact
-          path: build-output/
+          path: build/ 
+
