build & pack8

diff --git a/.github/workflows/package.yml b/.github/workflows/package.yml
--- a/.github/workflows/package.yml
+++ b/.github/workflows/package.yml
@@ -1,12 +1,12 @@
 name: Package and Upload
 
 on:
-    workflow_call:
-      inputs:
-        LANGUAGE:
-          description: "Programming Language to Package"
-          required: true
-          type: string
+  workflow_call:
+    inputs:
+      LANGUAGE:
+        description: "Programming Language to Package"
+        required: true
+        type: string
 
 jobs:
   package:
@@ -16,26 +16,38 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2  
 
-      - name: Download build artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: build-artifact
+      - name: Set package name and version
+        id: set_name
+        run: |
+            echo "Checking GITHUB_REF: $GITHUB_REF"
+            FOLDER_NAME="nexus-git-development"
+  
+            if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+              TAG_NAME="${GITHUB_REF#refs/tags/}"
+              git fetch origin master
+              MASTER_COMMIT=$(git rev-parse origin/master)
+              TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
+              if [[ "$TAG_COMMIT" == "$MASTER_COMMIT" ]]; then
+                export PACKAGE_ID="nexus-git-${TAG_NAME}"
+                export PACKAGE_VERSION="${TAG_NAME}"
+              else
+                echo "Error: Tags must be created on the master branch."
+                exit 1
+              fi
+            elif [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
+              export PACKAGE_ID="${FOLDER_NAME}.nexus-git"
+              export PACKAGE_VERSION="1.0.0-${GITHUB_RUN_ID}"
+            elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
+              COMMIT_ID=$(echo "${GITHUB_SHA}" | cut -c1-6)
+              export PACKAGE_ID="nexus-git-1.0.0-release-${COMMIT_ID}"
+              export PACKAGE_VERSION="1.0.0-release-${COMMIT_ID}"
+            elif [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
+              exit 1
+            fi 
+  
+            echo "PACKAGE_ID=${PACKAGE_ID}" >> $GITHUB_ENV
+            echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
 
-    #   - name: Build project
-    #     run: |
-    #         if [[ "${{ inputs.LANGUAGE }}" == "dotnet" ]]; then
-    #           dotnet build --configuration Release
-    #         elif [[ "${{ inputs.LANGUAGE }}" == "java" ]]; then
-    #            mvn clean package \
-    #             -Dpackage.id=${{ env.PACKAGE_ID }} \
-    #             -Dpackage.version=${{ env.PACKAGE_VERSION }}
-    #         elif [[ "${{ inputs.LANGUAGE }}" == "python" ]]; then
-    #           python setup.py install
-    #         elif [[ "${{ inputs.LANGUAGE }}" == "kotlin" ]]; then
-    #           gradle build
-    #         elif [[ "${{ inputs.LANGUAGE }}" == "react" || "${{ inputs.LANGUAGE }}" == "javascript" ]]; then
-    #           npm run build
-    #         fi
       - name: Pack project
         run: |
           echo "Packaging with version: $PACKAGE_VERSION"
@@ -57,9 +69,20 @@ jobs:
           fi
           echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> $GITHUB_ENV
 
-   
       - name: Upload Package as Artifact
         uses: actions/upload-artifact@v3
         with:
-          name: nuget-package
+          name: package-artifact
           path: ${{ env.ARTIFACT_PATH }}
+
+      - name: Download Package Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: package-artifact
+          path: ./downloaded-artifacts
+
+      - name: Use Artifact
+        run: |
+          echo "Using downloaded artifact from ./downloaded-artifacts"
+          # Example: Check the contents of the downloaded artifact
+          ls ./downloaded-artifacts
